name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # O 'master', asegúrate de que sea tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # La carpeta que creó react-scripts
          branch: gh-pages # La rama donde se subirá el sitio